MVCBase/Models/VesselVisit/CreateVesselVisitViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCBase.Models.VesselVisit
{
    public class CreateVesselVisitViewModel
    {
        public string VesselVisitNumber { get; set; }
        public string Linea { get; set; }

    }
}

MVCBase/Controllers/VesselVisitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCBase.Models.VesselVisit;

namespace MVCBase.Controllers
{
    public class VesselVisitController : Controller
    {
        // GET: VesselVisit
        [HttpGet]
        public ActionResult Index()
        {
            return View(new CreateVesselVisitViewModel());
        }

        [HttpPost]
        public ActionResult Index(CreateVesselVisitViewModel modeloCreacionVesselVisit)
        {
            if (ModelState.IsValid)
            {
                
            }
            return RedirectToAction("Index");
        }
    }
}

MVCBase/Views/VesselVisit/Index.cshtml
@model MVCBase.Models.VesselVisit.CreateVesselVisitViewModel


@using (Html.BeginForm("Index", "VesselVisit", FormMethod.Post))
{
    <div class="jarviswidget">
        <header>
            <h2>Create VesselVisit </h2></header>
        <div class="widget-body">
            <div class="form-group">
                @Html.LabelFor(x => x.Linea, new {@class = "col-lg-2"})
                <div class="col-lg-4">
                    @Html.TextBoxFor(x => x.Linea, new {@class = "form-control"})
                </div>
            </div>
        </div>

    </div>

    <div class="form-actions">
        <button class="btn btn-success" type="submit">Submit test</button>
    </div>
}